apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    
    scrape_configs:

      # ── OTel Collector (OTLP metrics pushed from all apps) ──────────────────
      - job_name: 'otel-collector'
        honor_labels: true
        params:
            format: ["openmetrics"]
        static_configs:
          - targets: ['otel-collector:8889']
